name: xmonad-config
author: Julius Marozas
github: jul1u5/dotfiles
copyright: Copyright (c) 2019 Julius Marozas
maintainer: marozas.julius@gmail.com
library:
  source-dirs: .
dependencies:
  - base >= 4.7 && < 5
  - xmonad
  - xmonad-contrib
executables:
  xmonad-config:
    source-dirs: .
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
