#!/usr/bin/env bash

OPTIONS=("Poweroff" "Reboot" "Suspend" "Hibernate")

LAUNCHER="rofi -width 15 -dmenu -i -p power"
USE_LOCKER="false"
LOCKER="i3lock"

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
    OPTIONS=("Exit" "${OPTIONS[@]}")
fi

option=$(printf '%s\n' "${OPTIONS[@]}" | $LAUNCHER | awk '{print $1}')
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval "$1"
        ;;
      Reboot)
        systemctl reboot
        ;;
      Poweroff)
        systemctl poweroff
        ;;
      Suspend)
        $USE_LOCKER && "$LOCKER"; systemctl suspend
        ;;
      Hibernate)
        $USE_LOCKER && "$LOCKER"; systemctl hibernate
        ;;
      *)
        ;;
    esac
fi
